# Generated by Django 3.2.23 on 2023-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0002_carddescription_carga_cargo_cliente_departamento_destinatario_empresatransportefluvial_motonave_muni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='Descripción',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='Destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='Origen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='Peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (Kg)'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='Tipo_carga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
