# Generated by Django 3.2.20 on 2023-09-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0002_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='email',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
