# Generated by Django 3.2.23 on 2023-11-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0003_auto_20231123_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='Estado_carga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='Fecha_transporte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
