# Generated by Django 3.2.20 on 2023-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0003_destinatario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='Canal_Radio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='motonave',
            name='celular',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
