# Generated by Django 3.2.23 on 2023-11-25 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0004_auto_20231125_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='Carga',
        ),
        migrations.AddField(
            model_name='viaje',
            name='Cargas',
            field=models.ManyToManyField(to='appFluvial.Carga'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='Remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_remitente', to='appFluvial.destinatario'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='Destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_destinatario', to='appFluvial.destinatario'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='Fecha_inicio_viaje',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='Motonave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appFluvial.motonave'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='Piloto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appFluvial.persona'),
        ),
    ]
