# Generated by Django 3.2.20 on 2023-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0004_auto_20230901_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='nombre_motonave',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
