# Generated by Django 3.2.20 on 2023-09-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0005_motonave_nombre_motonave'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appFluvial.cliente'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='Destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appFluvial.destinatario'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='Peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (Kg)'),
        ),
        migrations.AlterField(
            model_name='motonave',
            name='Capacidad_carga',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Capacidad (Kg)'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='Guía_zarpe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Guía zarpe'),
        ),
    ]
