# Generated by Django 3.2.23 on 2023-11-30 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0007_auto_20231125_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pagoefectivo', 'Pago en efectivo'), ('pagotransferencia', 'Pago por transferencia')], max_length=20)),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titular_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_transaccion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='viaje',
            name='Pagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appFluvial.pago'),
        ),
    ]
