# Generated by Django 3.2.20 on 2023-09-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0007_carddescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddescription',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='carddescription',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carddescription',
            name='text',
            field=models.CharField(blank=True, max_length=3000, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='carddescription',
            name='time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiempo'),
        ),
    ]
