# Generated by Django 3.2.23 on 2023-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0008_auto_20231129_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo',
        ),
        migrations.AddField(
            model_name='pago',
            name='pagoefectivo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagotransferencia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
