# Generated by Django 3.2.23 on 2023-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0009_auto_20231129_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pagoefectivo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pagotransferencia',
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=100),
        ),
    ]
