# Generated by Django 3.2.23 on 2023-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0011_alter_pago_valor_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tipo_pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='pagoefectivo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagotransferencia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
