# Generated by Django 3.2.23 on 2023-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0014_auto_20231201_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='factorSeguro',
            field=models.CharField(blank=True, default='0.15', max_length=255, null=True),
        ),
    ]
