# Generated by Django 3.2.23 on 2023-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0015_alter_carga_factorseguro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='parameter',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
