# Generated by Django 3.2.23 on 2023-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFluvial', '0016_auto_20231201_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='max',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='min',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
