# Generated by Django 3.1.2 on 2020-10-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='nombreRoll',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='userid',
        ),
        migrations.CreateModel(
            name='RollUser',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('rollid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roll')),
            ],
        ),
    ]
