# Generated by Django 3.1.2 on 2020-10-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201016_2129'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roll',
            table='roll',
        ),
        migrations.AlterModelTable(
            name='rolluser',
            table='roll_user',
        ),
    ]
