# Generated by Django 3.1.2 on 2020-10-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Negrilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='Subrayado',
            field=models.BooleanField(default=False),
        ),
    ]
