# Generated by Django 3.1.2 on 2020-10-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201016_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='idPadre',
            field=models.IntegerField(default=False, verbose_name='idPadre'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
