# Generated by Django 3.1.2 on 2020-10-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dependencia_detalleuser_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='justifiacion',
            field=models.CharField(max_length=1000),
        ),
    ]
