# Generated by Django 3.1.2 on 2020-10-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201019_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='justifiacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horaIngreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horaSalida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='justificacion',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
