# Generated by Django 3.1.2 on 2020-10-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201019_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='observacion',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
