# Generated by Django 3.1.2 on 2020-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_solicitud_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='observacion',
            new_name='observacionjefeI',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciontalentoH',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
