# Generated by Django 3.1.2 on 2020-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201020_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fechaModificacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
