# Generated by Django 3.1.2 on 2020-11-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_solicitud_fechamodificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permitido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'db_table': 'Permitido',
            },
        ),
    ]
