# Generated by Django 3.1.2 on 2020-11-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_permitido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='jefeInmeddiato',
            new_name='jefeInmediato',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horaEntrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='temperatura',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
